"""Initial operational schema: machines, telemetry, predictions, incidents.

Revision ID: 0001
Revises:
Create Date: 2026-09-23

Hand-written rather than autogenerated, because generating it requires a live
database connection.

Alembic builds these tables using the naming convention from `Base.metadata`, so
how a constraint must be named here depends on whether that convention's
template contains `%(constraint_name)s`:

* The ``pk`` and ``fk`` templates do not, so those names are given in full and
  used verbatim.
* The ``ck`` template does, so a CHECK constraint is given only its *suffix*.
  Passing the full name would have the convention wrap it a second time, giving
  ``ck_predictions_ck_predictions_failure_probability_range`` -- which is exactly
  what happened before this was corrected.

Naming constraints at all matters because PostgreSQL otherwise invents names
that a later migration cannot reliably reference when altering or dropping them.

`uv run alembic -c apps/api/alembic.ini check` verifies this migration still
agrees with the models. If it reports differences, this file is what is wrong.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Literal copies of the domain enums. Frozen here on purpose: a migration is a
#: historical record, so it must keep describing the schema as it was, even
#: after the enums gain members. Widening one of these is a new migration.
_RISK_LEVELS = ("NORMAL", "WARNING", "HIGH", "CRITICAL")
_SEVERITIES = ("LOW", "MEDIUM", "HIGH", "CRITICAL")
_STATUSES = ("OPEN", "ACKNOWLEDGED", "RESOLVED", "DISMISSED")
_INCIDENT_TYPES = ("BEARING_DEGRADATION", "OVERHEATING", "OVERLOAD", "UNCLASSIFIED")


def _in_clause(column: str, values: tuple[str, ...]) -> str:
    """Render a SQL `IN` expression from literal allowed values."""
    return f"{column} IN ({', '.join(repr(value) for value in values)})"


def upgrade() -> None:
    """Create the operational schema."""
    op.create_table(
        "machines",
        sa.Column("machine_id", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("machine_id", name="pk_machines"),
    )

    op.create_table(
        "telemetry",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("machine_id", sa.String(length=16), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("vibration", sa.Float(), nullable=False),
        sa.Column("rpm", sa.Float(), nullable=False),
        sa.Column("current", sa.Float(), nullable=False),
        sa.Column("load", sa.Float(), nullable=False),
        sa.Column("voltage", sa.Float(), nullable=False),
        sa.Column("simulation_session_id", sa.String(length=64), nullable=True),
        # The event identifier is the primary key, which is what makes
        # redelivery idempotent: a duplicate cannot be inserted at all.
        sa.PrimaryKeyConstraint("event_id", name="pk_telemetry"),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.machine_id"],
            name="fk_telemetry_machine_id_machines",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_telemetry_machine_id_recorded_at",
        "telemetry",
        ["machine_id", "recorded_at"],
    )

    op.create_table(
        "predictions",
        sa.Column("prediction_id", sa.String(length=36), nullable=False),
        sa.Column("machine_id", sa.String(length=16), nullable=False),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_probability", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("horizon_seconds", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("prediction_id", name="pk_predictions"),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.machine_id"],
            name="fk_predictions_machine_id_machines",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "failure_probability >= 0.0 AND failure_probability <= 1.0",
            name="failure_probability_range",
        ),
        sa.CheckConstraint(
            _in_clause("risk_level", _RISK_LEVELS),
            name="risk_level_valid",
        ),
        sa.CheckConstraint(
            "horizon_seconds > 0",
            name="horizon_positive",
        ),
    )
    op.create_index(
        "ix_predictions_machine_id_predicted_at",
        "predictions",
        ["machine_id", "predicted_at"],
    )

    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("machine_id", sa.String(length=16), nullable=False),
        sa.Column("incident_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("failure_probability", sa.Float(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("prediction_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("incident_id", name="pk_incidents"),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.machine_id"],
            name="fk_incidents_machine_id_machines",
            ondelete="CASCADE",
        ),
        # SET NULL rather than CASCADE: losing the originating prediction must
        # not delete the incident, which is an independent record of something
        # that happened.
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.prediction_id"],
            name="fk_incidents_prediction_id_predictions",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "failure_probability >= 0.0 AND failure_probability <= 1.0",
            name="failure_probability_range",
        ),
        sa.CheckConstraint(
            _in_clause("severity", _SEVERITIES),
            name="severity_valid",
        ),
        sa.CheckConstraint(
            _in_clause("status", _STATUSES),
            name="status_valid",
        ),
        sa.CheckConstraint(
            _in_clause("incident_type", _INCIDENT_TYPES),
            name="incident_type_valid",
        ),
    )
    op.create_index(
        "ix_incidents_machine_id_detected_at",
        "incidents",
        ["machine_id", "detected_at"],
    )
    op.create_index(
        "ix_incidents_status_detected_at",
        "incidents",
        ["status", "detected_at"],
    )


def downgrade() -> None:
    """Drop the operational schema."""
    op.drop_index("ix_incidents_status_detected_at", table_name="incidents")
    op.drop_index("ix_incidents_machine_id_detected_at", table_name="incidents")
    op.drop_table("incidents")

    op.drop_index("ix_predictions_machine_id_predicted_at", table_name="predictions")
    op.drop_table("predictions")

    op.drop_index("ix_telemetry_machine_id_recorded_at", table_name="telemetry")
    op.drop_table("telemetry")

    op.drop_table("machines")
