"""Simulation runs: the record of what the dashboard asked the simulator to do.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26

Hand-written rather than autogenerated, for the reason 0001 gives: generating one
requires a live database connection.

The enum values are literal copies, frozen here on purpose. A migration is a
historical record of what the schema was at this revision, so deriving them from
`RunStatus` at run time would make an old migration produce a different table
depending on when it ran. `alembic check` is what keeps these copies honest.

`uv run alembic -c apps/api/alembic.ini check` verifies this agrees with the
models. If it reports differences, this file is what is wrong.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Literal copies of `RunStatus` and `SimulationScenario` as they stood at this
#: revision. See the module docstring.
RUN_STATUSES = ("PENDING", "RUNNING", "COMPLETED", "STOPPED", "FAILED")
ACTIVE_RUN_STATUSES = ("PENDING", "RUNNING")
SCENARIOS = ("NORMAL", "BEARING_DEGRADATION", "OVERHEATING", "OVERLOAD")

_ACTIVE_PREDICATE = "status IN ('PENDING', 'RUNNING')"


def upgrade() -> None:
    """Create the simulation runs table."""
    op.create_table(
        "simulation_runs",
        sa.Column("session_id", sa.String(length=32), primary_key=True),
        sa.Column("machine_id", sa.String(length=16), nullable=False),
        sa.Column("scenario", sa.String(length=32), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sample_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("tick_seconds", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_ticks", sa.Integer(), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", sa.String(length=255), nullable=True),
        sa.Column("resume_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.machine_id"],
            name="fk_simulation_runs_machine_id_machines",
            ondelete="CASCADE",
        ),
        # Given as the suffix only: the `ck` naming template contains
        # `%(constraint_name)s`, so passing a full name would have the
        # convention wrap it a second time -- the trap 0001 records.
        sa.CheckConstraint("sample_interval_seconds > 0", name="sample_interval_positive"),
        sa.CheckConstraint("duration_seconds > 0", name="duration_positive"),
        sa.CheckConstraint("tick_seconds >= 0.0", name="tick_seconds_non_negative"),
        sa.CheckConstraint("completed_ticks >= 0", name="completed_ticks_non_negative"),
        sa.CheckConstraint("resume_count >= 0", name="resume_count_non_negative"),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'COMPLETED', 'STOPPED', 'FAILED')",
            name="status_valid",
        ),
        sa.CheckConstraint(
            "scenario IN ('NORMAL', 'BEARING_DEGRADATION', 'OVERHEATING', 'OVERLOAD')",
            name="scenario_valid",
        ),
    )

    op.create_index(
        "ix_simulation_runs_machine_id_created_at",
        "simulation_runs",
        ["machine_id", "created_at"],
    )
    op.create_index(
        "ix_simulation_runs_status_created_at",
        "simulation_runs",
        ["status", "created_at"],
    )

    # At most one active run per machine. Both supported dialects have partial
    # indexes, so this is a schema guarantee rather than a convention the use
    # cases have to remember -- two runs on one machine would interleave two
    # scenarios' readings on the same charts, with nothing logged to say why.
    op.create_index(
        "uq_simulation_runs_active_machine",
        "simulation_runs",
        ["machine_id"],
        unique=True,
        postgresql_where=sa.text(_ACTIVE_PREDICATE),
        sqlite_where=sa.text(_ACTIVE_PREDICATE),
    )


def downgrade() -> None:
    """Drop the simulation runs table."""
    op.drop_index("uq_simulation_runs_active_machine", table_name="simulation_runs")
    op.drop_index("ix_simulation_runs_status_created_at", table_name="simulation_runs")
    op.drop_index("ix_simulation_runs_machine_id_created_at", table_name="simulation_runs")
    op.drop_table("simulation_runs")
