"""The maintenance corpus: documents, their versions, and their embedded chunks.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26

Hand-written rather than autogenerated, for the reason 0001 gives: generating one
requires a live database connection.

The category values are literal copies, frozen here on purpose. A migration is a
historical record of what the schema was at this revision, so deriving them from
`DocumentCategory` at run time would make an old migration produce a different
table depending on when it ran. `alembic check` is what keeps these copies
honest.

Two things about the vector column are worth knowing before reading further:

* The extension is created here rather than assumed. Supabase may install it
  into a schema other than `public` (its documentation recommends `extensions`);
  the type reference below is unqualified and resolves through `search_path`, so
  either location works. Which schema it actually lands in is recorded in the
  changelog once observed against the live project.
* No ANN index is created, deliberately -- see the comment above
  `ix_knowledge_chunks_document_id`.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Literal copies of `DocumentCategory` and of the embedding width, as they
#: stood at this revision. See the module docstring.
CATEGORIES = (
    "MOTOR_MAINTENANCE_MANUAL",
    "BEARING_INSPECTION",
    "OVERHEATING_TROUBLESHOOTING",
    "VIBRATION_DIAGNOSIS",
    "ELECTRICAL_SAFETY",
    "PREVENTIVE_MAINTENANCE_SCHEDULE",
    "SENSOR_CALIBRATION",
    "LUBRICATION",
    "STATOR_WINDING_TEST",
    "INCIDENT_RESPONSE",
)
EMBEDDING_DIMENSIONS = 384

_CATEGORY_CHECK = "category IN (" + ", ".join(f"'{value}'" for value in CATEGORIES) + ")"


def _embedding_type() -> sa.types.TypeEngine[Any]:
    """Return the vector column's type for the dialect this migration runs on.

    PostgreSQL gets pgvector; anything else gets JSON, because the vector type
    only exists where the extension is installed and a migration that cannot run
    against SQLite cannot be checked with `alembic check` locally.
    """
    if op.get_bind().dialect.name == "postgresql":
        return Vector(EMBEDDING_DIMENSIONS)
    return sa.JSON()


def upgrade() -> None:
    """Create the corpus tables, and the extension the vector column needs."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "knowledge_documents",
        sa.Column("document_id", sa.String(length=36), primary_key=True),
        sa.Column("document_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("source_path", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "document_key",
            "version",
            name="uq_knowledge_documents_key_version",
        ),
        # Suffix only: the `ck` naming template contains `%(constraint_name)s`,
        # so a full name would be wrapped a second time -- the trap 0001 records.
        sa.CheckConstraint(_CATEGORY_CHECK, name="category_valid"),
        sa.CheckConstraint("page_count > 0", name="page_count_positive"),
        sa.CheckConstraint("document_key <> ''", name="document_key_not_blank"),
        sa.CheckConstraint("version <> ''", name="version_not_blank"),
    )
    op.create_index(
        "ix_knowledge_documents_document_key",
        "knowledge_documents",
        ["document_key"],
    )
    # At most one active version of a document, enforced by the schema rather
    # than by a check-then-insert: activation supersedes, and two active versions
    # would make "the current procedure" ambiguous.
    op.create_index(
        "uq_knowledge_documents_active_key",
        "knowledge_documents",
        ["document_key"],
        unique=True,
        postgresql_where=sa.text("is_active"),
        sqlite_where=sa.text("is_active"),
    )

    op.create_table(
        "knowledge_chunks",
        sa.Column("chunk_id", sa.String(length=36), primary_key=True),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=255), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("embedding", _embedding_type(), nullable=False),
        sa.Column("embedding_model", sa.String(length=96), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.document_id"],
            name="fk_knowledge_chunks_document_id_knowledge_documents",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name="uq_knowledge_chunks_document_index",
        ),
        sa.CheckConstraint("char_count > 0", name="char_count_positive"),
        sa.CheckConstraint("page > 0", name="page_positive"),
        sa.CheckConstraint("chunk_index >= 0", name="chunk_index_non_negative"),
    )
    # No ANN index, deliberately. The corpus is tens of chunks, not thousands:
    # ivfflat would need its `lists` tuned against the row count (a common
    # starting point of rows/1000 is degenerate here) and an untuned one reduces
    # recall by scanning only the nearest few lists, while HNSW would
    # accelerate a sequential scan a table this size already wins. Without
    # either, `<=>` is an exact KNN -- better results, sub-millisecond.
    #
    # Add HNSW (m=16, ef_construction=64) when the corpus reaches roughly ten
    # thousand chunks, and measure recall before and after.
    op.create_index(
        "ix_knowledge_chunks_document_id",
        "knowledge_chunks",
        ["document_id"],
    )


def downgrade() -> None:
    """Drop the corpus tables.

    The extension is left installed: other things may use it, and dropping a
    type that columns elsewhere depend on is not this migration's decision.
    """
    op.drop_index("ix_knowledge_chunks_document_id", table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index("uq_knowledge_documents_active_key", table_name="knowledge_documents")
    op.drop_index("ix_knowledge_documents_document_key", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
