/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream fleet changes as they happen
         * @description Push a hint whenever a machine changes.
         *
         *     **The payload is a hint, not the data.** Each frame names a machine and what
         *     changed about it; the client responds by refetching the REST endpoint that
         *     owns that representation. So the stream never becomes a second source of
         *     truth, a missed frame is repaired by the next one, and the JSON here has no
         *     schema to drift from the ones the rest of the API serves.
         *
         *     The frame shape is deliberately mirrored by hand in the frontend
         *     (`apps/web/src/realtime/types.ts`), because a `text/event-stream` body
         *     cannot be described in OpenAPI and so cannot be generated from it.
         *     `apps/api/tests/integration/test_events_api.py` pins the field names and
         *     every `EventKind` value, so renaming either here fails the Python suite
         *     rather than silently freezing the browser.
         *
         *     Unguarded, and it has to be: `EventSource` cannot set request headers, so no
         *     `X-Ingest-Token` can ever be presented to this route.
         */
        get: operations["stream_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List incidents
         * @description Return incidents across the fleet, most recent first.
         *
         *     Both filters are optional and combine conjunctively. The enum types are
         *     validated by the framework, so an unknown status yields a 422 rather than an
         *     empty list that would look like "no incidents".
         */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change an incident's lifecycle status
         * @description Move an incident to a new status.
         *
         *     The only write in this API that is **not** behind `X-Ingest-Token`, and
         *     that is a decision rather than an oversight. The dashboard calls it from a
         *     browser, so guarding it would mean shipping the shared secret to every
         *     client -- the thing unguarded reads exist to avoid. The exposure is bounded:
         *     incidents are the only mutable resource reachable without a token, and
         *     closing one cannot inject telemetry, register a machine, or alter a
         *     prediction. Phase 11 owns operator authentication and closes it. See ADR
         *     0007.
         *
         *     This is also what keeps incident suppression from being permanent. An
         *     incident is raised only when a machine has none open, so until one can be
         *     resolved, no later excursion on that machine can ever file another.
         */
        patch: operations["update_incident_status_api_v1_incidents__incident_id__patch"];
        trace?: never;
    };
    "/api/v1/machines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List machines
         * @description Return the fleet with each machine's latest observed and predicted state.
         *
         *     Returns an empty list when no machines are registered, which is the
         *     expected state before the simulator exists.
         */
        get: operations["list_machines_api_v1_machines_get"];
        put?: never;
        /**
         * Register a machine
         * @description Add a machine to the fleet, or return the one already registered.
         *
         *     Idempotent, because the pipeline declares its fleet on start without
         *     tracking what it declared last time. The status code distinguishes the two
         *     outcomes: 201 when this call created the machine, 200 when it already
         *     existed.
         */
        post: operations["register_machine_api_v1_machines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/machines/{machine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get machine detail
         * @description Return one machine's current state and recent incidents.
         *
         *     The identifier is parsed into a domain value object here rather than
         *     validated by the framework, so a malformed identifier produces the same
         *     error shape as any other domain validation failure.
         */
        get: operations["get_machine_api_v1_machines__machine_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/machines/{machine_id}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get incidents for a machine
         * @description Return incidents raised for one machine, most recent first.
         */
        get: operations["get_machine_incidents_api_v1_machines__machine_id__incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/machines/{machine_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get prediction history
         * @description Return how the predicted failure risk has changed over time.
         */
        get: operations["get_predictions_api_v1_machines__machine_id__predictions_get"];
        put?: never;
        /**
         * Score a machine from its stored telemetry
         * @description Ask the model about a machine, and store what it said.
         *
         *     Takes no body. The window comes from telemetry already stored for the
         *     machine, which is what the pipeline persists before anything scores it --
         *     so the ordering the model depends on is the API's responsibility rather
         *     than a caller's.
         */
        post: operations["record_prediction_api_v1_machines__machine_id__predictions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/machines/{machine_id}/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a machine's simulation runs
         * @description Return a machine's runs, newest first.
         *
         *     A sub-resource rather than a field on `GET /machines/{id}`, so the machine's
         *     simulation panel can poll at its own cadence -- several seconds while a run
         *     is active -- without dragging the whole detail response with it.
         */
        get: operations["list_machine_simulations_api_v1_machines__machine_id__simulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/machines/{machine_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get telemetry history
         * @description Return telemetry for a machine over a window.
         *
         *     Longer windows are aggregated server-side before transmission. The response
         *     states the resolution it was reduced to, so a caller can always tell
         *     measurements from aggregates.
         */
        get: operations["get_telemetry_api_v1_machines__machine_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List simulation runs
         * @description Return recent runs across the fleet, newest first.
         *
         *     A run's `is_active` and `is_stale` are computed by the API. A client must
         *     never derive either: staleness needs a clock and a timeout, and a browser
         *     reading its own clock would disagree with the server about whether a run is
         *     alive.
         */
        get: operations["list_simulations_api_v1_simulations_get"];
        put?: never;
        /**
         * Start a simulation run
         * @description Begin a run on a machine.
         *
         *     **Unguarded**, like the incident actions and for the same reason: the
         *     dashboard calls it from a browser, and a token in a browser bundle is not a
         *     boundary but the appearance of one. The exposure is larger here than for an
         *     incident, though -- a run costs CPU on a box that already shares one core
         *     between the API, the orchestrator and the model service -- so it is bounded
         *     instead: one active run per machine, a ceiling on concurrent runs, and a
         *     floor on duration that refuses a run too short to produce anything. See ADR
         *     0008.
         */
        post: operations["start_simulation_api_v1_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Reset a simulation run
         * @description Discard a finished run's record so the machine is free for another.
         *
         *     It does **not** delete the telemetry the run produced, and cannot: deleting
         *     stored readings is a destructive write, which would have to be guarded by
         *     the ingest token, which a browser cannot hold. So a second run appends to a
         *     machine's charts rather than replacing them -- which the windowed charts
         *     hide in practice, and which the runbook says out loud.
         */
        delete: operations["reset_simulation_api_v1_simulations__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Report a run's state
         * @description Accept a state report from the simulator service.
         *
         *     **The one guarded route here**, and the guard is on the route rather than
         *     the router because this router mixes browser traffic with machine traffic.
         *     That is not a weakness in the usual arrangement -- it is the point: the
         *     caller is a service, exactly like n8n, and `ingest_api_token`'s own
         *     docstring calls it "one machine proving to another that it is the expected
         *     caller". A browser is structurally unable to forge a completion, which the
         *     three dashboard routes above cannot say.
         *
         *     Progress reports are accepted without publishing an event. The service
         *     reports every few seconds; announcing each one would make every open
         *     dashboard refetch on that cadence for a progress bar.
         */
        patch: operations["report_simulation_state_api_v1_simulations__session_id__patch"];
        trace?: never;
    };
    "/api/v1/simulations/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a simulation run
         * @description End a run.
         *
         *     A separate route from `DELETE` because the two mean different things:
         *     stopping ends a run and keeps the record of it, and resetting discards the
         *     record once the run has ended. Collapsing them would make "stop" silently
         *     destroy the history a demonstration is worth reviewing.
         *
         *     Idempotent, and it terminalises the run whatever the simulator says -- an
         *     escape hatch that could fail to close would leave a run stuck at RUNNING
         *     with no way out but the database.
         */
        post: operations["stop_simulation_api_v1_simulations__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of telemetry
         * @description Store readings, tolerating redelivery.
         *
         *     A redelivered batch is not an error. It reports `accepted: 0` and a
         *     `duplicates` count equal to the batch size, because the transport is
         *     at-least-once and a retry is an expected event rather than a fault.
         */
        post: operations["ingest_telemetry_api_v1_telemetry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Report that the process is running.
         *
         *     Deliberately does not touch the database: a liveness probe answers "should
         *     this process be restarted?", and a database outage is not fixed by
         *     restarting the API.
         */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Report whether the service can serve requests.
         *
         *     Unlike liveness, this does check the database -- readiness answers "should
         *     this instance receive traffic?", and an instance that cannot reach its
         *     database should be taken out of rotation rather than restarted.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aggregation
         * @description How points within a bucket were combined.
         * @enum {string}
         */
        Aggregation: "RAW" | "MEAN" | "MIN" | "MAX";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Result of a health check.
         */
        HealthResponse: {
            /**
             * App Env
             * @description Which environment this process is running in.
             */
            app_env: string;
            /** Detail */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * IncidentSchema
         * @description A maintenance incident.
         */
        IncidentSchema: {
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Failure Probability */
            failure_probability: number;
            /** Incident Id */
            incident_id: string;
            /** @description Failure mode. Currently always UNCLASSIFIED: the predictive model detects rising failure risk but does not identify its cause. */
            incident_type: components["schemas"]["IncidentType"];
            /** Machine Id */
            machine_id: string;
            /**
             * Prediction Id
             * @description The prediction that triggered this incident, when known.
             */
            prediction_id?: string | null;
            /** @description Severity at the time the incident was raised. */
            severity: components["schemas"]["IncidentSeverity"];
            status: components["schemas"]["IncidentStatus"];
        };
        /**
         * IncidentSeverity
         * @description How severe an individual incident is judged to be.
         * @enum {string}
         */
        IncidentSeverity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /**
         * IncidentStatus
         * @description Lifecycle state of a maintenance incident.
         * @enum {string}
         */
        IncidentStatus: "OPEN" | "ACKNOWLEDGED" | "RESOLVED" | "DISMISSED";
        /**
         * IncidentType
         * @description Category of a detected failure condition.
         * @enum {string}
         */
        IncidentType: "BEARING_DEGRADATION" | "OVERHEATING" | "OVERLOAD" | "UNCLASSIFIED";
        /**
         * IngestResultSchema
         * @description What became of a batch.
         *
         *     `ready` names the machines that now hold a full prediction window, which is
         *     what the orchestrator uses to decide when to ask for a prediction.
         */
        IngestResultSchema: {
            /**
             * Accepted
             * @description Records stored by this call.
             */
            accepted: number;
            /**
             * Duplicates
             * @description Records dropped because their event_id existed.
             */
            duplicates: number;
            /**
             * Ready
             * @description Machines holding a complete prediction window.
             */
            ready: string[];
        };
        /**
         * MachineDetailSchema
         * @description Consolidated view of one machine.
         */
        MachineDetailSchema: {
            /** Recent Incidents */
            recent_incidents: components["schemas"]["IncidentSchema"][];
            summary: components["schemas"]["MachineSummarySchema"];
        };
        /**
         * MachineSchema
         * @description A machine's registry identity.
         */
        MachineSchema: {
            /** Machine Id */
            machine_id: string;
            /** Name */
            name: string;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
        };
        /**
         * MachineSummarySchema
         * @description A machine with its latest observed and predicted condition.
         *
         *     `latest_telemetry` and `latest_prediction` are independently nullable: a
         *     machine that is registered but silent has neither, and one that has stopped
         *     reporting keeps its last known values so staleness is visible rather than
         *     presenting as health.
         *
         *     **Nullable but not optional**, and the distinction reaches the frontend.
         *     Pydantic gives a field with a default a `null` type *and* removes it from
         *     OpenAPI's `required` list, so a generated client sees `T | null | undefined`
         *     and a check for `null` alone leaves `undefined` in the else-branch -- which
         *     compiles and then throws on the first machine that has not been scored. No
         *     route uses `exclude_none`, so these are always sent; declaring them required
         *     makes the generated types say what the wire already does.
         */
        MachineSummarySchema: {
            /**
             * Is Reporting
             * @description Whether any telemetry has ever been received for this machine.
             */
            is_reporting: boolean;
            latest_prediction: components["schemas"]["PredictionSchema"] | null;
            latest_telemetry: components["schemas"]["TelemetryRecordSchema"] | null;
            machine: components["schemas"]["MachineSchema"];
            /** Open Incident Count */
            open_incident_count: number;
            /** @description Risk band from the latest prediction; null if none exists yet. */
            risk_level: components["schemas"]["RiskLevel"] | null;
        };
        /**
         * PredictionSchema
         * @description A model prediction, as stored at the time it was made.
         */
        PredictionSchema: {
            /**
             * Failure Probability
             * @description Model output, not a certainty. See the API's safety notice.
             */
            failure_probability: number;
            /**
             * Horizon Seconds
             * @description How far ahead the prediction looks.
             */
            horizon_seconds: number;
            /** Machine Id */
            machine_id: string;
            /** Model Version */
            model_version: string;
            /**
             * Predicted At
             * Format: date-time
             */
            predicted_at: string;
            /** Prediction Id */
            prediction_id: string;
            /** @description Application band derived from the probability at prediction time. */
            risk_level: components["schemas"]["RiskLevel"];
        };
        /**
         * RegisterMachineRequest
         * @description A machine to add to the registry.
         *
         *     The length bounds mirror the columns. `Machine.__post_init__` validates the
         *     timestamp but not the name -- only `rename` does -- so an empty name would
         *     otherwise reach the database and persist.
         */
        RegisterMachineRequest: {
            /**
             * Machine Id
             * @description Fleet-unique identifier, as published in telemetry.
             */
            machine_id: string;
            /**
             * Name
             * @description Human-readable label.
             */
            name: string;
        };
        /**
         * ReportSimulationStateRequest
         * @description A state report from the simulator service.
         */
        ReportSimulationStateRequest: {
            /** Completed Ticks */
            completed_ticks?: number | null;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * ResolvedWindowSchema
         * @description The instants a series actually covers.
         *
         *     `window` names a duration; this says where that duration was applied. The
         *     two can differ, and a client that assumed otherwise would misplace the
         *     whole series on a time axis: the end is the newest stored reading whenever
         *     that leads the wall clock, which is exactly what happens while a simulator
         *     is being played back faster than real time.
         */
        ResolvedWindowSchema: {
            /**
             * End
             * Format: date-time
             * @description Where the series ends. Later than the wall clock during a fast-forwarded simulation, because it follows the data.
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /**
         * RiskLevel
         * @description Application-level risk derived from a model's failure probability.
         * @enum {string}
         */
        RiskLevel: "NORMAL" | "WARNING" | "HIGH" | "CRITICAL";
        /**
         * RunStatus
         * @description Where a run has got to.
         * @enum {string}
         */
        RunStatus: "PENDING" | "RUNNING" | "COMPLETED" | "STOPPED" | "FAILED";
        /**
         * SensorReadingSchema
         * @description The six telemetry signals.
         */
        SensorReadingSchema: {
            /**
             * Current
             * @description Motor current draw.
             */
            current: number;
            /**
             * Load
             * @description Mechanical load.
             */
            load: number;
            /**
             * Rpm
             * @description Shaft speed.
             */
            rpm: number;
            /**
             * Temperature
             * @description Winding or housing temperature.
             */
            temperature: number;
            /**
             * Vibration
             * @description Velocity RMS.
             */
            vibration: number;
            /**
             * Voltage
             * @description Supply voltage.
             */
            voltage: number;
        };
        /**
         * SeriesResolutionSchema
         * @description How a returned series was reduced.
         *
         *     Exposed because a consumer must be able to tell a measurement from an
         *     aggregate. The PRD's evidence model treats those differently, and hiding
         *     the distinction here would make it impossible to honour later.
         */
        SeriesResolutionSchema: {
            aggregation: components["schemas"]["Aggregation"];
            /**
             * Bucket Seconds
             * @description Bucket width in seconds, or null when the series is raw.
             */
            bucket_seconds?: number | null;
            /** Is Raw */
            is_raw: boolean;
        };
        /**
         * SimulationRunSchema
         * @description A simulation run, as the dashboard sees it.
         */
        SimulationRunSchema: {
            /** Completed Ticks */
            completed_ticks: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Detail
             * @description Why a run failed or was stopped without the simulator's confirmation.
             */
            detail?: string | null;
            /**
             * Duration Seconds
             * @description Simulated time the run covers.
             */
            duration_seconds: number;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Is Active
             * @description Whether the run is still going.
             */
            is_active: boolean;
            /**
             * Is Stale
             * @description Whether an active run has stopped reporting, which means the simulator service is gone or unreachable. Derived by the API, never by a client: it needs a clock and a timeout, and a browser has neither.
             */
            is_stale: boolean;
            /** Machine Id */
            machine_id: string;
            /**
             * Sample Interval Seconds
             * @description Simulated time between readings.
             */
            sample_interval_seconds: number;
            scenario: components["schemas"]["SimulationScenario"];
            /** Seed */
            seed: number;
            /** Session Id */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Tick Count
             * @description How many readings the run produces.
             */
            tick_count: number;
        };
        /**
         * SimulationScenario
         * @description What a run drives the machine towards.
         * @enum {string}
         */
        SimulationScenario: "NORMAL" | "BEARING_DEGRADATION" | "OVERHEATING" | "OVERLOAD";
        /**
         * StartSimulationRequest
         * @description A run to begin.
         *
         *     The four fields `PRD.md` §11 names -- machine, scenario, duration, and
         *     seed/demo mode -- and nothing else. Playback speed is deliberately not among
         *     them: the spec does not list it, and a caller setting a fast pace on a
         *     one-core box is the failure mode the resource limits exist to bound.
         */
        StartSimulationRequest: {
            /**
             * Demo
             * @description Use the canonical PRD section 12 demonstration: bearing degradation and a fixed seed, so the sequence is always the same one. Supplies only what the caller left unset -- an explicit scenario or seed still wins.
             * @default false
             */
            demo: boolean;
            /**
             * Duration Minutes
             * @description Simulated time to cover, not wall-clock time. At least 60 minutes, because the model needs that many readings before it will predict anything -- a shorter run produces no risk band and no incident, and looks identical to a broken pipeline.
             * @default 240
             */
            duration_minutes: number;
            /** Machine Id */
            machine_id: string;
            /** @description Required unless `demo` is set, which supplies the demonstration's own. */
            scenario?: components["schemas"]["SimulationScenario"] | null;
            /**
             * Seed
             * @description Omit for a fixed default seed.
             */
            seed?: number | null;
        };
        /**
         * TelemetryIngestItem
         * @description One reading, as the simulator emits it.
         *
         *     `session_id` carries the name the simulator uses; the domain and the column
         *     call the same thing `simulation_session_id`. Renaming happens here, at the
         *     boundary, rather than in either of them.
         */
        TelemetryIngestItem: {
            /** Current */
            current: number;
            /**
             * Event Id
             * @description Idempotency key. Redelivering one of these creates no second row.
             */
            event_id: string;
            /** Load */
            load: number;
            /** Machine Id */
            machine_id: string;
            /**
             * Recorded At
             * Format: date-time
             * @description When the reading was taken, with a UTC offset.
             */
            recorded_at: string;
            /** Rpm */
            rpm: number;
            /** Session Id */
            session_id?: string | null;
            /** Temperature */
            temperature: number;
            /** Vibration */
            vibration: number;
            /** Voltage */
            voltage: number;
        };
        /**
         * TelemetryIngestRequest
         * @description A batch of readings from the transport.
         */
        TelemetryIngestRequest: {
            /**
             * Records
             * @description Oldest first. A redelivered batch is accepted and reported as duplicates.
             */
            records: components["schemas"]["TelemetryIngestItem"][];
        };
        /**
         * TelemetryPointSchema
         * @description One point on a telemetry series.
         */
        TelemetryPointSchema: {
            reading: components["schemas"]["SensorReadingSchema"];
            /**
             * Sample Count
             * @description 1 for a raw measurement, otherwise the number of readings combined.
             */
            sample_count: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * TelemetryRecordSchema
         * @description A single stored telemetry record.
         */
        TelemetryRecordSchema: {
            /**
             * Event Id
             * @description Idempotency key from the transport layer.
             */
            event_id: string;
            /** Machine Id */
            machine_id: string;
            reading: components["schemas"]["SensorReadingSchema"];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /**
         * TelemetrySeriesSchema
         * @description A window of telemetry at a stated resolution.
         */
        TelemetrySeriesSchema: {
            interval: components["schemas"]["ResolvedWindowSchema"];
            /** Machine Id */
            machine_id: string;
            /** Points */
            points: components["schemas"]["TelemetryPointSchema"][];
            resolution: components["schemas"]["SeriesResolutionSchema"];
            window: components["schemas"]["TimeWindow"];
        };
        /**
         * TimeWindow
         * @description A selectable history window.
         * @enum {string}
         */
        TimeWindow: "1h" | "5h" | "24h" | "7d" | "30d";
        /**
         * UpdateIncidentStatusRequest
         * @description A requested lifecycle transition.
         *
         *     The target is a status rather than an action, mirroring the domain: the
         *     permitted moves are a table over statuses, and expressing the request the
         *     same way keeps the router from holding a second copy of that table.
         *
         *     `OPEN` is a valid value of this enum but never a valid target -- nothing
         *     transitions back to it. That is a 409 rather than a 422, because the request
         *     is well formed and the incident's current state is what refuses it.
         */
        UpdateIncidentStatusRequest: {
            status: components["schemas"]["IncidentStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    stream_events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                /** @description Return only incidents in this lifecycle state. */
                status?: components["schemas"]["IncidentStatus"] | null;
                /** @description Return only incidents of this severity. */
                severity?: components["schemas"]["IncidentSeverity"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_incident_status_api_v1_incidents__incident_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIncidentStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_machines_api_v1_machines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineSummarySchema"][];
                };
            };
        };
    };
    register_machine_api_v1_machines_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMachineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_machine_api_v1_machines__machine_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_machine_incidents_api_v1_machines__machine_id__incidents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_predictions_api_v1_machines__machine_id__predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_prediction_api_v1_machines__machine_id__predictions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_machine_simulations_api_v1_machines__machine_id__simulations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry_api_v1_machines__machine_id__telemetry_get: {
        parameters: {
            query?: {
                /** @description History window to return. */
                window?: components["schemas"]["TimeWindow"];
            };
            header?: never;
            path: {
                machine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetrySeriesSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_simulations_api_v1_simulations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_simulation_api_v1_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_simulation_api_v1_simulations__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_simulation_state_api_v1_simulations__session_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportSimulationStateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_simulation_api_v1_simulations__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_telemetry_api_v1_telemetry_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResultSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
